### ISSUE TITLE
REG asks - Azure Challenges

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/dymechh#10]
- Scaling up VM to GPUs
    - Set up FTP
    - Connect to RStudio/Jupyter with the VPN
    - Remounting Fileshare

**Comment by dingaaling** [comment]
Iain chat on 4 Aug:
- New GPU machine needs to be set up at later date
- TBD on FTP
- Need to figure out Rstudio with IT
- Fileshare sorted

**Comment by RuthBowyer** [comment]
VM fileshare seems to need remounting again for it to be found, so for some reason the fix was temporary! I will dig in my history the steps Ian took previously to fix, and see if the secret is within! 

Followed up with Ian last week about Rstudio/Jupyter access without VPN - he followed up with IT.

**Comment by AoifeHughes** [comment]
Hi, 

Rather than create a separate issue, can we (REG) share some thoughts we've had on the current Azure usage? 

Following some of our initial work + discussions @crangelsmith and I, seem to have hit a major stopping block due to Azure storage space. 

To better frame the discussion and estimate potential costs, we've the following questions: 
- How long is the data and project expected to last (there's the possibility of Azure offering storage discounts for longer hosting periods)?
- There's currently no backup in place, is there budget available to consider this?
- Is there any possibility of more datasets being required or added that would need to be hosted in the current Azure storage? 

We're currently investigating options available and discussing with other members of REG (will update here when we have a better idea of the Azure pricing model, but knowing budget limitations will also be useful)

**Comment by dingaaling** [comment]
Flagging for @RuthBowyer that we should bring this up with Gavin this week!

**Comment by crangelsmith** [comment]
Also want to add that for the SPC work we need to create a batch account and a dedicated storage account under the Dyme subscription.

**Comment by AoifeHughes** [comment]
For storage cost reference: 

- @crangelsmith found that we can switch from the current 5TB option to 100TB and only pay for what we use 
    - https://learn.microsoft.com/en-us/azure/storage/files/understanding-billing
- Estimated costs for different storage amounts can be calculated here: https://azure.microsoft.com/en-gb/pricing/details/storage/files/
    - Based on this it might also be worth deciding on "upper limits" of what would be acceptable. 
    - This would allow us to impose our own caps on what we use.  
    - For reference, it seems the current pricing on our 5TB system is ~£104 per 30 days
    - Scaling this to the maximum of 100TB (which, I believe, is much more than we currently would have need for) would verge on £1800 per 30 days. 
    - Hence why having a firm limit would be useful.

**Comment by RuthBowyer** [comment]
Thanks so much for flagging this! will discuss with Gavin - it's not very sustainable long term with these costs is my concern! I'm wondering what our stakeholders currently use to store their data as well given much of the variables are for them. 

We could replace most of the files with bias corrected ones when we have run all of the assessments on the methods though, so at present can't forsee it going much over 10TB...

**Comment by dingaaling** [comment]
Hey folks, I'm planning to make a request for 10,000 (as advised by Tomas) on [Mathison](https://turingcomplete.topdesk.net/tas/public/ssp/content/serviceflow?unid=fabf0809069f42a5a36c61d677da08fa&openedFromService=true) which should be the amount we have allocated (our upper limit) until March 2023.

@AoifeHughes + @crangelsmith do these points look like the right ones to cite for our cost estimates?
- For reference, it seems the current pricing on our 5TB system is ~£104 per 30 days
- Based on @RuthBowyer's estimate we want to increase to 10-20TB?
- Potential need for a new VM for SPC work?

Tomas has also kindly shared these resources:

- The easiest way to check this information is to use the RC TAB webapp: https://rcp-api-prod.azurewebsites.net/
Past spending
- [Monthly cost by resource for the past six months](https://portal.azure.com/#@turing.ac.uk/blade/Microsoft_Azure_CostManagement/Menu/open/CostAnalysis/scope/%2Fsubscriptions%2F6b9576b1-432c-4a06-a1b2-d178f1e08850/view/H4sIAAAAAAAAA41SXU%2FbQBD8L%2Ffs0BJCFHhLCI2QqB3Fpi8VijbnjTlxvnPvA9WN%2FN%2B7aycttA%2FweLszc7OzexAyOodGtuJarBZrkYgSAm7AVEiVe%2FBh%2BtWa8OSp8yOiI9xBhLbh7ry2LqhfWN5YHwYm5BgYUTkwUYNTgYV7Bd0SBKrKYQVBWdML2QC6Z9PDQM2qR7F9NHKAiTzWokv%2Bgh%2Fy5T94rvxPIY5nh6YS198PolQOT33wEk3JneSks1BaU6H3KrrHhGawsTmRjyMvVY3Gs8Yf3ga9jU5iwYjukY0SaO%2BGbmoNsnn5BC6wsQDymRPTsWYRkDLWlFTAkrp70B6p2qgXG%2Fw7H%2BfoXpTElF9d8hGL91YO0X8MvuIABnmKw0vbE3zceelUw0L%2B08X%2BHGY4no4QcDyaXF5cja4uxzD6DNPz2QTleDIDUn5u1JtxFrGskNeseOybLC%2B26fzb3WpeZJuzxcNydVtss3Vxl6X5WZqlt4REAzvNKQUXkZ4%2FA20Qy7UjW7Rk9K9v4n3B7lUGXyxdBvRn9%2BYXHrtUvtHQpoNwPVzydte6Y0gssZ2K7jdkaa%2FgSgMAAA%3D%3D)
- [Daily cost by resource for the past thirty days](https://portal.azure.com/#@turing.ac.uk/blade/Microsoft_Azure_CostManagement/Menu/open/CostAnalysis/scope/%2Fsubscriptions%2F6b9576b1-432c-4a06-a1b2-d178f1e08850/view/H4sIAAAAAAAAA41SXU%2FjQAz8L%2FucctAWVHhrG65CQknVpLycEDIbN6xIdnP7gS5X5b%2BfndCDwgM8rj0zOx57L2SwFrVsxZVYLdYiEgV43IAukSq34PzkNIbWUeN3QEuwvfBtw815baxXf7FYGucHImToGVFa0KECqzzrxqCqlgBQlhZL8MroXsZ4qHouPTTUrPkqtQtaDjCRhVp00Rt4m8Uf8Fz5TCGOY3%2B6FFe%2F9qJQFg99cBJ1wZ3ooLN1UGJMk4vuPiL7JjQH5uu0sapROxb4T9qgM8FKzBnR3bNLAu3s0E2MRnYun8B6duVBPnNYVahZBKQMNYXksaDuDiqHVG3Ui%2FHui48ztC9KYsKvLvqOxVsjh9y%2FB19xAIM8xeGk6QkuPDppVcNC7sdkdwYzHF%2BMEHA8mp5PLkeX52MYncLF2WyKcjydASk%2FN%2BponEUoSuQdKx57mWb5QzK%2Fu1nN83RzstjGq%2Bv8IV3nN2mSnSRpck1I1PBYcUreBqTnH0%2Frw2JtyRZtGN37g%2FhasHuXwU9DZwH9zR39wmMXyjUVtMkg3B8xn5sT3T%2Bo9DY9NgMAAA%3D%3D)
Current and projected spending
- [Cost by resource this month](https://portal.azure.com/#@turing.ac.uk/blade/Microsoft_Azure_CostManagement/Menu/open/CostAnalysis/scope/%2Fsubscriptions%2F6b9576b1-432c-4a06-a1b2-d178f1e08850/view/H4sIAAAAAAAAA41Sy07DQAz8lz2nPEpBhVtLoEKCpGpSLgghs3HTFclu2AeiVPl37IZCgQMc156Z9Yy9FjJYi1quxJmYjKciEgV4nIEukSr5Urkbo%2F2S6s8BLaHWwq8a7o1qY716w%2BLcON%2FxIEPPiNKCDhVY5Vk2BlWtCABlabEEr4zeyBgP1YZLDw01a35ILYKWHUxkoRZt9AWeZ%2FEPPFd%2BU4jjeD5dirO7tSiUxW0fnERdcCfa6swdlBiTcdHeRzS%2BCc2W%2BeE2VjVqxwKfpBk6E6zEnBHtPU9JoIXtuonRyJPLJVjPcVkEDkHKUFM2HgsqehuQio16Md798V2G9kVJTPjVRv8Z7NrILu3%2FwSdsu5OnEJw0G4ILj05a1bCQ2z9aHMIQ%2Byc9BOz3BsdHp73T4z70DuDkcDhA2R8M2eVTo77ZGYeiRN6sYtfnaZY%2FJKPbq8koT2d743k8ucgf0ml%2BlSbZXpImF4REDY8Vh8QZ0fPV09KwmFoai%2FaKbvcM%2FhZsdzK4NHQMsLm0b7%2Bw7UK5poJV0gmPvrbFp%2BZE%2Bw4wtbHgMQMAAA%3D%3D)
- [Cost by resource this year](https://portal.azure.com/#@turing.ac.uk/blade/Microsoft_Azure_CostManagement/Menu/open/CostAnalysis/scope/%2Fsubscriptions%2F6b9576b1-432c-4a06-a1b2-d178f1e08850/view/H4sIAAAAAAAAA41SXW%2FbMAz8L3p2ujVNi7RvSdMFBTY7iN0BxVAUrMw4wmzJo6RiWeD%2FPtJu%2BrE9tI8i7068I%2FdKRyK0eqcu1HK%2BUokqIeAabIVcKbbG3yIQl39FJAbtVdi10po1joL5g%2BWl82GgQY5BEBWBjTWQCaL6zdmwrXcMgaoirCAYZ3shF6Du2fyw0Ijqk9gmWj3AVB4b1SUv4Jt88Q9eKv9TmONlQlupix97VRrCQx%2B8RltKJznozE1dc6GfVXV3CXtwsT2QnywvTIPWi8Yzb43eRdJYCKK7k0EZtKGhmzqLMrzeAgXJjBAkB61jwwEFLLkYKCIXW%2FPogn%2Fnuxzp0WhM5dUlHxnsq9ND4B%2BDL8X2IM8heO16go8PXpNpRch%2FOtkcwxTHZyMEHI8mpyfno%2FPTMYw%2Bw9nxdIJ6PJmKy5%2BteWNnHssKZblGXF9meXGfzr5fL2dFtj6a3yyWV8V9tiquszQ%2FSrP0ipFo4aGWkCQjfv4OvDcsV8Rj8WrRv76E9wW7Vxl8cXwP0B%2Fbm1%2FEdml8W8MuHYRnL9uSa%2FOq%2BwsySNt7NQMAAA%3D%3D)
