### ISSUE TITLE
Share CHESS-SCAPE UKCP2.2 data with LCAT - ask them for their data to compare

### ISSUE THREAD

**Issue by RuthBowyer** [alan-turing-institute/dymechh#16]
- Review the CHESS-SCAPE data that the LCAT team is using and compare to UKCP 2.2 data
- Compare CHESS-SCAPE before BA/after BA
- Summarise results in a document to share with Then Try This team

**Comment by dingaaling** [comment]
see: docs/CHESS-SCAPE-Review.html
