### ISSUE TITLE
Download rest of the UKCP18 2.2km climate variables

### ISSUE THREAD

**Issue by RuthBowyer** [alan-turing-institute/dymechh#27]
- Add folders for missing climate variables
- Download from CEDA missing data (only have tasmax and pr for now), see markdown: https://github.com/alan-turing-institute/dymechh/blob/main/data/data_recalibration/Downloading-HADs-data.md 
- [RB]: Push handy scripts

**Comment by crangelsmith** [comment]
Link to the data to dowload: https://data.ceda.ac.uk/badc/ukcp18/data/land-cpm/uk/2.2km

Variables to download

- [x] Cloud cover (clt) 
- [x] Precipitation (pr) m
- [ ] ~Radiation, total downward short wave flux (rsds) W/m2~ (not available at 2.2 km)
- [x] Radiation, net long wave (rls) 
- [x] Relative humidity (hurs) 
 - [x] Snow: snowfall amount mm/day * (prsn)
- [x] Snow: lying snow amount mm/day*  (snw)
- [x] Specific humidity (huss) 
- [x] Temperature, maximum (tasmax)
- [x] Temperature, mean (tas) 
- [x] Temperature, minimum (tasmin) 
- [x] 3-hourly Wind speed (sfcWind) 
- [x] Wind speed eastwards (uas) 
- [x] Wind speed northwards (vas)

**Comment by crangelsmith** [comment]
All of the variables have been downloaded into the fileshare in here: https://dymestorage1.file.core.windows.net/vmfileshare/ClimateData/Raw/UKCP2.2.

Closing the issue now.
