### ISSUE TITLE
Download the HADsUK grid

### ISSUE THREAD

**Issue by RuthBowyer** [alan-turing-institute/dymechh#29]
Tasmin to be downloaded (tasmax and pr already done): https://data.ceda.ac.uk/badc/ukmo-hadobs/data/insitu/MOHC/HadOBS/HadUK-Grid/v1.1.0.0/1km 

[RB]: - Obs time for other variables -- ask panel? -- what time period where not daily

**Comment by crangelsmith** [comment]
We now have downloaded all tasmin in `/vmfileshare/ClimateData/Raw/HadsUKgrid` with the script from #32 

> 744  files dowloaded from  /badc/ukmo-hadobs/data/insitu/MOHC/HadOBS/HadUK-Grid/v1.1.0.0/1km/tasmin/day/v20220310

**Comment by RuthBowyer** [comment]
Hey there - refreshing my memory where we are with this:
In ```/vmfileshare/ClimateData/Raw/HadsUKgrid```
we have ```rainfall```, ```tasmax``` and ```tasmin``` 

Am I right in thinking either we didn't download the other data because they weren't available daily, or was it because you folks worked out we could mount directly to the CEDA database for this and we didn't need to? Apologies for not remembering!

And if the former, why did we not also download ```tas``` ?

Thanks so much!

**Comment by crangelsmith** [comment]
Hi @RuthBowyer, I think only those 3 variables have a daily granularity (this is the case for [tas](https://data.ceda.ac.uk/badc/ukmo-hadobs/data/insitu/MOHC/HadOBS/HadUK-Grid/v1.1.0.0/1km/tas) as well). 

If we were going to use more variables is probably better to mount the CEDA database. The only dataset that i think is worth storing is the BNG simulations projected by us that are not available anywhere else.
