### ISSUE TITLE
Resample HADS 1km grid to 2.2km grid

### ISSUE THREAD

**Issue by RuthBowyer** [alan-turing-institute/dymechh#30]
### Summary

We need to resample the HadsUK grid to 2.2km grid 

### What needs to be done?

- [x] RB to share resampling method
- [ ] Key to ensure the 2.2km spatially aligns with the UKCP18 

### Who can help?

Dyme Team!

### Updates

* [Replace this sentence to provide a status summary after the issue has been opened. To avoid others from reading through the full thread of comments, please share updates (e.g. decisions taken) regularly.]

**Comment by AoifeHughes** [comment]
Commit https://github.com/alan-turing-institute/dymechh/commit/7abb21fc9235af619e5f2c24dd86c57f43591b2a adds the initial version by RB for reference.

**Comment by AoifeHughes** [comment]
- Putting a pin in finishing this to after discussions with team (more pressing project tasks to give attention to)
- I think the best solution may involve using gdalwrap
    - https://gdal.org/programs/gdalwarp.html
- Another solution might be to tie this up with https://github.com/alan-turing-institute/dymechh/issues/28 
    - There might be scope to do some of the bias adjustments in memory and not need to save intermediate steps to disk
        - BUT, I'm not sure - need to think about it more

**Comment by RuthBowyer** [comment]
Moved and completed via `clim-recal` see [here](https://github.com/alan-turing-institute/clim-recal/issues/2)
