### ISSUE TITLE
Follow-up email to Met Office about advisory panel & next steps

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/dymechh#36]

**Comment by dingaaling** [comment]
Hi all,

Thank you for the interesting discussion last week (and for the invitation to Stats & Snacks, Laura!) about a potential collaboration around CLIM-RECAL, and a repo of bias correction methods & resources to support broader applications of the UKCP18 datasets.

Following up on that conversation, here are a few recap points:
- Discussion centred on on technical points of collaboration (e.g. different calibration data sources, uni/multivariate methods, ) as well as on community resources (e.g. repo of methods, guidance), particularly for those in different sectors
- CLIM-RECAL team aims to have first iteration of repo of methods (including formal literature review) by March/April and are seeking advisors to guide their work so it links with UKCP/other Met Office resources
- Open question on what the best UKCP resource looks like (ideally not a set of pre-computed datasets, but rather a repo of methods and guidance on how to choose a method)

And questions:
- Would members from your team be open to serving as advisors on CLIM-RECAL, perhaps one from a technical standpoint and another from a strategic standpoint?
- For Fai - might you be able to introduce our team (Ruth, Gavin, & myself) to someone from the HadUK team and also potentially the Danish Met Office contact (Mark Payne)?
- Might you be available for a follow-up discussion in early December to share some initial results from our team and sense-check that we are building in a direction that aligns with larger UKCP plans?
- Additionally, are there any suggestions for how to best engage in this collaboration, for example through an MoU or to potentially bring in another gov organisation to ensure the sustainability of the work? (e.g. data hosting)

Hope to speak again soon,
Jennifer

**Comment by RuthBowyer** [comment]
This is great, thanks Jenn!! Only a minor edit, but a couple of comments I didnt want to put inline: 

> Might you be available for a follow-up discussion around 28-30 November to share some initial results from our team and sense-check that we are building in a direction that aligns with larger UKCP plans?

This feels potentially too soon, depending what we want to show them (I'm thinking a cleaned up iteration of the table, a structural outline of the review?) - but def good to do this year! Maybe we could do first week of December if AL allows?

> for example through an MOU or to potentially bring in another gov organisation 

I don't know what an MOU (memo of understanding?) is or does - please ignore if this is a standard abrev (i am a sheltered academic)
