### ISSUE TITLE
Draft stakeholder briefing questions for call

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/dymechh#43]
Final document to send to stakeholders: https://docs.google.com/document/d/1E79CWyu5U8_U7hJ15crgz8UrU0RPhOh_XPABNu-7Ecc/edit?usp=sharing

Once #42 is complete, draft a pre-workshop stakeholder brief. Here are suggested questions, as drawn from:
- [Met Office workshop breakout questions](https://hackmd.io/08kcTobpR5Gt5RlhasESaQ?view#Breakout-Rooms---Public-Health)
- [Met office workshop pre-workshop survey](https://forms.office.com/Pages/ResponsePage.aspx?id=p_SVQ1XklU-Knx-672OE-UMJ-OLeNnBFi2Rhg69Mc1BUMTQzUlBBOUtSVDQ5VVpCQzU0NFRGTFUzMS4u)

# Suggested Pre-Workshop Questions

## General Info
- Could you please describe your background
- What country are you representing?
- What is your organisation/affiliation and role?

## Climate data background
- What prior work has your team or organisation done with climate data? Which specific climate datasets did you use?
- Is there a geographic area of your country you are most interested in?
- Is there a time period that you are most interested in? (e.g. present day, next 5-10 years, next 10-20 years, 30+ years)

## Application areas of interest
- What are the primary health-related questions that you are using climate data to help answer in your organisation?
- What kinds of actions/decisions/interventions will be taken based on these answers? What are the timelines on which these decisions happen?
- What kinds of climate hazards are most important to consider for public health in your country/organisation? (e.g. flooding, heatwaves)?
- What approaches do you take for quantifying risk/vulnerability to different population groups? What kinds of interventions are you considering?

## Closing info
- What is your primary interest in the workshop, and what do you hope to get out of it?
- Is there a topic from your country/organisation you'd like to highlight at the workshop? In particular we'd like to learn about examples of climate adaptation or mitigation actions you've taken to improve public health outcomes.

**Comment by dingaaling** [comment]
@aranas thoughts on these pre-workshop questions? please do update any of these points as you see fit!

**Comment by aranas** [comment]
this looks great! I think it would be interesting to learn more about the population health data they have available (if any). 
- What is the granularity and coverage (time & space) of the health data collected? who owns that data?

Was your idea to send these questions out prior to the workshop, such that the responses can help us prepare? Will we get a chance to do a video call with some of the the workshop participants?
