### ISSUE TITLE
Summarize stakeholder info as result of pre-workshop interviews

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/dymechh#47]
We want to record any info and stakeholder personas.
This info could be shared with Turing team prior to the workshop, it can then be updated with information collected during the workshop

**Comment by aranas** [comment]
@dingaaling I started mapping out some stakeholder personas (will send document privately)

I think it might be interesting to have a workshop goal in mind for each of them. The goals might change as we get to know them better during prework or during workshop but making this explicit can help us guide our interactions. What do you think, do you think the format I chose could be helpful also when sharing with wider Turing team?

**Comment by dingaaling** [comment]
https://docs.google.com/document/d/1E79CWyu5U8_U7hJ15crgz8UrU0RPhOh_XPABNu-7Ecc/edit?usp=sharing
