### ISSUE TITLE
Provide Briefing & Blurb about the Fringe event

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/dymechh#48]
# Fringe Event Briefing & Blurb

Briefing: https://hackmd.io/xYObvRvuQEazJvTpURhT8Q?both

Blurb below👇

## AIUK Fringe Event: Responsible AI in Climate Change and Public Health

In conjunction with the AI for Climate workshop, we are organizing an afternoon fringe event - on Feb 13th - focused on the responsible use of AI in climate change and public health. This event, organized in collaboration with Turing, CSIRO, and CAIDE, will feature a panel discussion and an interactive activity to engage the audience. The objective of the fringe event is to enable a multidisciplinary dialogue among experts in AI, climate change, and public health as well as increase skills & capabilities for identifying and managing risks in this context.

While this fringe event is independent of the workshop, it shares thematic overlap; discussions will center around a case study for an AI-based microsimulation tool. The event will set the stage for our 2 day workshop by providing context and a broader view on the values and challenges of the proposed AI-based solution, enriching the workshop's content with foundational insights. It also presents a unique opportunity for you to meet and engage with the local community of practitioners and researchers, with plenty of room for networking and collaboration.

**Comment by dingaaling** [comment]
### Suggested edits

AIUK Fringe Event: Responsible AI in Climate Change and Public Health 
Date: 13 February 2024 
Location: TBD Melbourne 
Time: TBD 

In conjunction with the AI for Climate workshop, you are also invited to a fringe event on the evening of Feb 13th focused on the responsible use of AI in climate change and public health. Organized in collaboration with Turing, CSIRO, and CAIDE, the objective of the event is to host a multidisciplinary panel discussion among experts in AI, climate change, and public health followed by an interactive activity for attendees to increase skills & capabilities for identifying and managing risks in this context. 

This fringe event will set the stage for our 2 day workshop by providing context and a broader view on the values and challenges of the proposed AI-based solution, enriching the workshop's content with foundational insights. It also presents a unique opportunity for you to meet and engage with the local community of practitioners and researchers, with plenty of room for networking and collaboration.

**Comment by aranas** [comment]
# Blurb for public comms / website

## Data-Driven Futures: Responsible AI in Climate and Health Policy

Join us at the AIUK Fringe Event, in collaboration with CAIDE & CSIRO's data61, for a focused exploration into responsible AI's role in developing climate-resilient health policies. This session will delve into the ethical challenges and governance issues of AI in the context of climate change and its affects on public health. Additionally, the event features a case study activity, focusing on practicing skills in identifying and managing risks associated with AI-supported decision making. This is an opportunity to deepen your understanding and enhance your ability to identify and find management solutions for risks associated with AI in health and environmental contexts.
## Agenda

_Please note the details below are subject to changes, with more details to come._

16:00 – 16:30  Welcome & Networking

16:30 – 17:20 Panel Discussion and Q&A

This multidisciplinary discussion will bring together experts to provide a comprehensive perspective on current research and innovations at the intersection of the field of AI, Climate Change and Health. The goal is to facilitate a productive exchange of ideas and insights that can inform future research and collaboration.

- **Panel**: 
    Prof. Didar Zowghi - Senior Principal Research Scientist and Diversity & Inclusion in AI Lead, CSIRO's Data 61
	Prof. Gavin Shaddick - Executive Dean of Engineering, Physical and Mathematical Sciences at Royal Holloway University of London
Prof. Jacqueline Peel - Director of Melbourne Climate Futures, University of Melbourne


17:20 - 18:30 Case Study activity
Dive into a real-world case study, designed to enhance your skills in identifying risks associated with AI in the realms of climate change and health. This session, supported by guiding material from The Alan Turing Institute, will provide practical experience in strategising effective solutions for AI-related challenges.

- **Lead**: Dr. Christopher Burr, Senior Researcher in Trustworthy Systems, The Alan Turing Institute


18:30 - 19:00 Plenary Discussion and Knowledge Share

19:00 - 19:30 Drinks

@dingaaling do you have a suggestion for which role to display for Gavin in this context? Any thought on title? (will share via email with everyone as well later, but posting here for reference

**Comment by dingaaling** [comment]
This looks incredible @aranas. Gavin's title is: Executive Dean of Engineering, Physical and Mathematical Sciences at Royal Holloway University of London (see: https://www.turing.ac.uk/people/researchers/gavin-shaddick)
