### ISSUE TITLE
New dask env + format to load/format data (Xarray)

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/dymechh#5]
Goals:
1. useful/easy to use for other users (non-engineers)
2. computational efficiency
 
To Do:
- Fernando to consult experts and document suggestions

**Comment by mfbenitezp** [comment]
I have asked some colleagued in UA where the following options were suggested to work on the clip, overlay, and transformation of format in bulk. 
- https://corteva.github.io/rioxarray/html/index.html
- https://docs.xarray.dev/en/stable/

- [ ] Install these tools
- [ ] Test a subset of data in the VM
- [ ] Get basis statistics to define if the approach is worthy

**Comment by mfbenitezp** [comment]
I've been holding this task as I have a deadline with ASPCIS for a more tuned model. I hope to returnt to this in my assigned day for DyME-CCH, next Fri 26th AUG.
